import { Project } from "./models/types";

export const mockProjects: Project[] = [
  // Проект 1
  {
    id: "1",
    name: "Проект 10796_T2",
    preparedBy: "Спасов А.",
    preparationDate: new Date().toISOString().split("T")[0],
    createdAt: "2025-06-10",
    locked: false, //можно редактировать
    approved: false,
    estimate: [
      {
        id: "1-1",
        section: "Отделочные работы",
        name: "Обои флизелиновые",
        costType: "Материалы",
        unit: "шт",
        plannedQuantity: 10,
        unitCost: 1500,
      },
      {
        id: "1-2",
        section: "Отделочные работы",
        name: "Покраска стен",
        costType: "Трудозатраты",
        unit: "м²",
        plannedQuantity: 45,
        unitCost: 300,
      },
    ],
    warehouse: [
      {
        id: "w1-1",
        projectId: "1",
        date: "2025-06-15",
        itemId: "1-1",
        actualQuantity: 8,
        comment: "Остаток на складе",
      },
    ],
  },
  // Проект 2
  {
    id: "2",
    name: "Проект 10700_MTC",
    preparedBy: "Спасов А.",
    preparationDate: new Date().toISOString().split("T")[0],
    createdAt: "2025-06-10",
    locked: false,
    approved: false,
    estimate: [
      {
        id: "2-1",
        section: "Конструкция",
        name: "ДСП 18мм",
        costType: "Материалы",
        unit: "шт",
        plannedQuantity: 5,
        unitCost: 3200,
      },
      {
        id: "2-2",
        section: "Освещение",
        name: "Светодиодная лента",
        costType: "Материалы",
        unit: "шт",
        plannedQuantity: 12,
        unitCost: 450,
      },
    ],
    warehouse: [
      {
        id: "w2-1",
        projectId: "2",
        date: "2025-07-05",
        itemId: "2-1",
        actualQuantity: 5,
        comment: "Полный расход",
      },
      {
        id: "w2-2",
        projectId: "2",
        date: "2025-07-06",
        itemId: "2-2",
        actualQuantity: 10,
        comment: "Частичный расход",
      },
    ],
  },
  // Проект 3
  {
    id: "3",
    name: "Книжный_мир_2025",
    preparedBy: "Козлова В.",
    preparationDate: new Date().toISOString().split("T")[0],
    createdAt: "2025-03-12",
    locked: false,
    approved: true,
    estimate: [
      {
        id: "3-1",
        section: "Конструкция",
        name: "Деревянные панели (сосна)",
        costType: "Материалы",
        unit: "м²",
        plannedQuantity: 20,
        unitCost: 1500,
      },
      {
        id: "3-2",
        section: "Мебель",
        name: "Стеллажи для книг",
        costType: "Аренда",
        unit: "компл.",
        plannedQuantity: 5,
        unitCost: 3000,
      },
      {
        id: "3-3",
        section: "Монтаж",
        name: "Сборка стенда",
        costType: "Трудозатраты",
        unit: "чел/час",
        plannedQuantity: 12,
        unitCost: 800,
      },
    ],
    warehouse: [
      {
        id: "w3-1",
        projectId: "3",
        date: "2025-04-01",
        itemId: "3-1",
        actualQuantity: 18,
        comment: "Остаток: 2 м² (брак)",
      },
    ],
  },
  // Проект 4
  {
    id: "4",
    name: "Pharma_2025_BioHealth",
    preparedBy: "Зайцева О.",
    preparationDate: new Date().toISOString().split("T")[0],
    createdAt: "2025-01-15",
    locked: false,
    approved: false,
    estimate: [
      {
        id: "4-1",
        section: "Основа",
        name: "Стеклянные перегородки",
        costType: "Материалы",
        unit: "м²",
        plannedQuantity: 15,
        unitCost: 4500,
      },
      {
        id: "4-2",
        section: "Логистика",
        name: "Доставка хрупких материалов",
        costType: "Услуги",
        unit: "компл.",
        plannedQuantity: 1,
        unitCost: 12000,
      },
      {
        id: "4-3",
        section: "Декор",
        name: "Печать на стекле (логотип)",
        costType: "Услуги",
        unit: "м²",
        plannedQuantity: 3,
        unitCost: 2000,
      },
    ],
    warehouse: [
      {
        id: "w4-1",
        projectId: "4",
        date: "2025-02-10",
        itemId: "4-1",
        actualQuantity: 15,
        comment: "Доставлено с защитной плёнкой",
      },
    ],
  },
];
